c_compiler_version:     # [osx]
  - 17                  # [osx]
cxx_compiler_version:   # [osx]
  - 17                  # [osx]

macos_machine:
  - arm64-apple-darwin20.0.0
cross_target_platform:
  - osx-arm64
gfortran_version:
  - 15.2.0
  - 14.3.0
gfortran_maj_ver:
  - 15
  - 14
libgfortran_soversion:
  - 5
  - 5
zip_keys:
  - - gfortran_version
    - gfortran_maj_ver
    - libgfortran_soversion
  - - cross_target_platform
    - macos_machine
